## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [11]:
import numpy as np
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [25]:
n = 2

np.array([1, 2, 3]*n)

array([1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [2]:
import numpy as np
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [1]:
import numpy as np
matrix = np.zeros((10, 10))
matrix[0, :] = 1
matrix[:, 0] = 1
matrix[9, :] = 1
matrix[:, 9] = 1
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [2]:
matrix = np.zeros((8, 8))
matrix[0 :: 2, 0 :: 2] = 1
matrix[1 :: 2, 1 :: 2] = 1
matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [6]:
def ij_sum_matrix(n):
    i, j = np.ogrid[:n, :n]
    return i+j
ij_sum_matrix(5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [7]:
vector1 = np.array([0, 1, 2, 3])
vector2 = np.array([3, 2, 1, 0])

matrix1 = np.array([
    [1, 2, 3, 4], 
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [5, 6, 7, 8]
])
matrix2 = np.array([
    [1, 1, 1, 1], 
    [1, 2, 3, 4], 
    [4, 3, 2, 1], 
    [4, 4, 4, 4]
])

print(str(np.vdot(vector1, vector2)) + ' - multiply vector by vector')
print('-------------------------------------')
print(str(np.dot(matrix1, vector1)) + ' - multiply matrix by vector')     
print('-------------------------------------')
print(str(np.dot(matrix1, matrix2)) + ' - multiply matrix by matrix') 

4 - multiply vector by vector
-------------------------------------
[20 20 44 44] - multiply matrix by vector
-------------------------------------
[[31 30 29 28]
 [31 30 29 28]
 [71 70 69 68]
 [71 70 69 68]] - multiply matrix by matrix


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [8]:
cos_x = np.cos(np.linspace(0, 1, int(1 / 0.05 + 1)))
sin_x = np.sin(np.linspace(0, 1, int(1 / 0.05 + 1)))
list(cos_x) + list(sin_x)

[1.0,
 0.9987502603949663,
 0.9950041652780258,
 0.9887710779360422,
 0.9800665778412416,
 0.9689124217106447,
 0.955336489125606,
 0.9393727128473789,
 0.9210609940028851,
 0.9004471023526769,
 0.8775825618903728,
 0.8525245220595057,
 0.8253356149096782,
 0.7960837985490559,
 0.7648421872844884,
 0.7316888688738209,
 0.6967067093471654,
 0.6599831458849821,
 0.6216099682706644,
 0.5816830894638835,
 0.5403023058681398,
 0.0,
 0.04997916927067833,
 0.09983341664682815,
 0.14943813247359924,
 0.19866933079506122,
 0.24740395925452294,
 0.2955202066613396,
 0.3428978074554514,
 0.3894183423086505,
 0.43496553411123023,
 0.479425538604203,
 0.5226872289306592,
 0.5646424733950355,
 0.6051864057360395,
 0.6442176872376911,
 0.6816387600233341,
 0.7173560908995228,
 0.7512804051402927,
 0.7833269096274834,
 0.8134155047893737,
 0.8414709848078965]

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [10]:
a = 4 * np.random.rand(3,5) - 1
a

array([[ 2.94012593,  0.17228655,  0.87769533,  1.93184594,  0.99885045],
       [ 1.82759303, -0.04520979,  2.56169856, -0.47755193,  0.1280213 ],
       [-0.53018751,  0.73858108,  0.98596891,  1.03303272,  1.55838686]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [13]:
summa = np.sum(a)
rows = np.sum(a, axis = 1)
columns = np.sum(a, axis = 0)
avg = np.mean(a, axis = 1)
disp = np.var(a, axis = 1)
otkl = np.std(a, axis = 1)
print(summa, ' - the sum of all elements of the matrix')
print(rows, ' - the sum inside the rows of the matrix')
print(columns, ' - the sum inside the columns of the matrix')
print(avg, ' - average value for each row')
print(disp, ' - variance for each row')
print(otkl, ' - standard deviation for each row')

14.701137415092491  - the sum of all elements of the matrix
[6.92080419 3.99455117 3.78578205]  - the sum inside the rows of the matrix
[4.23753144 0.86565784 4.4253628  2.48732673 2.68525862]  - the sum inside the columns of the matrix
[1.38416084 0.79891023 0.75715641]  - average value for each row
[0.91891941 1.39151944 0.48560651]  - variance for each row
[0.95860284 1.17962682 0.69685473]  - standard deviation for each row


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [14]:
for i in range(len(a)):
    a[i, :] = (a[i, :] - np.mean(a[i])) / np.std(a[i])
a

array([[ 1.62315927, -1.26420895, -0.52833716,  0.57133682, -0.40194998],
       [ 0.87204086, -0.71558226,  1.49436101, -1.08208981, -0.5687298 ],
       [-1.84736341, -0.02665596,  0.32835035,  0.39588783,  1.14978118]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [15]:
col = a[:, 2]
sort = col.argsort()
a = a[sort]
a

array([[ 1.62315927, -1.26420895, -0.52833716,  0.57133682, -0.40194998],
       [-1.84736341, -0.02665596,  0.32835035,  0.39588783,  1.14978118],
       [ 0.87204086, -0.71558226,  1.49436101, -1.08208981, -0.5687298 ]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [16]:
matr_b = np.dot(np.transpose(a), a)
matr_c = np.dot(a, np.transpose(a))
print(matr_b, ' - matrix В')
print(matr_c, ' - matrix С')

[[ 6.80785285 -2.6267862  -0.16101393 -0.74760457 -3.27244815]
 [-2.6267862   2.11099278 -0.41016214  0.04148238  0.88447319]
 [-0.16101393 -0.41016214  2.62006893 -1.78890138 -0.25999147]
 [-0.74760457  0.04148238 -1.78890138  1.65407129  0.84095229]
 [-3.27244815  0.88447319 -0.25999147  0.84095229  1.80701414]]  - matrix В
[[ 5.         -3.37431526  1.14094343]
 [-3.37431526  5.         -2.1835289 ]
 [ 1.14094343 -2.1835289   5.        ]]  - matrix С


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [17]:
np.sum(np.diagonal(matr_b)) + np.sum(np.diagonal(matr_c))

30.000000000000004

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [20]:
det_b = np.linalg.det(b)
det_c = np.linalg.det(c)
rank_a = np.linalg.matrix_rank(a)
rank_b = np.linalg.matrix_rank(b)
rank_c = np.linalg.matrix_rank(c)
w_b, v_b = np.linalg.eig(b)
w_c, v_b = np.linalg.eig(c)

print(f'Ранг матрицы А: {rank_a}\nДетерминант матрицы B: {det_b}\nРанг матрицы B: {rank_b}\n' \
      f'Спектр матрицы B: {w_b}\nДетерминант матрицы C: {det_c}\nРанг матрицы C: {rank_c}\n' \
      f'Спектр матрицы C: {w_c}\n')


NameError: name 'b' is not defined

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [23]:
#number 2
np.random.seed(17)
print(np.random.randint(9))
def f(x):
    return (x+1)/(x**3-x**2)

def integral(f, a, b, dx):
    """
    Ввод: функция f(x), начало и конец отрезка [a;b], шаг интегрирования
    
    Вывод: значение интеграла функции f(x) на отрезке [a;b]
    """
    N = int((b-a) / dx)  # количество шагов
    xk = np.linspace(a, b, N)  # точки
    rectan = dx*np.sum(f(xk))  # решение методом прямоугольников
    trapezoid = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  # решение методом трапеций
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))  # решение методом Симпсона
    return f"{rectan}, {trapezoid}, {simp} при шаге интегрирования {dx}"

anal_solution = np.float64(10.35203026391961716592062485020723)  # аналитическое решение
print(f"{anal_solution} - аналитическое решение функции f(x) на отрезке [3;4]")

for i in range(6):
    print(integral(f, -2, -1, 0.1 * 0.1**i))

"""Мы видим, что при уменьшении dx уменьшается разница между аналитическим решением и тремя численными выше. Происходит это
за счёт увеличения числа шагов N и числа точек xk."""

1
10.352030263919618 - аналитическое решение функции f(x) на отрезке [3;4]
0.0715080883938078, -6.047936356050637, -4.009935917709719 при шаге интегрирования 0.1
0.07426904095182782, -50.93666530248251, -33.93322124473947 при шаге интегрирования 0.010000000000000002
0.07525503921081832, -500.9258292951235, -333.9254823614969 при шаге интегрирования 0.0010000000000000002
0.07535323830134504, -5000.92475510503, -3333.9247203857017 при шаге интегрирования 0.00010000000000000003
0.07536305428293223, -50000.924647779146, -33333.92464430695 при шаге интегрирования 1.0000000000000003e-05
0.07536403584189473, -500000.9246370472, -333333.9246367001 при шаге интегрирования 1.0000000000000004e-06


'Мы видим, что при уменьшении dx уменьшается разница между аналитическим решением и тремя численными выше. Происходит это\nза счёт увеличения числа шагов N и числа точек xk.'

In [24]:
def f(x):
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def integral(f, a, b, dx):
    """
    Ввод: функция f(x), начало и конец отрезка [a;b], шаг интегрирования
    
    Вывод: значение интеграла функции f(x) на отрезке [a;b]
    """
    N = int((b-a) / dx)  # количество шагов
    xk = np.linspace(a, b, N)  # точки
    rectan = dx*np.sum(f(xk))  # решение методом прямоугольников
    trapezoid = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  # решение методом трапеций
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))  # решение методом Симпсона
    return f"{rectan}, {trapezoid}, {simp} при шаге интегрирования {dx}"

anal_solution = np.float64(1.110720734539591561753970247515173)  # аналитическое решение
print(f"{anal_solution} - аналитическое решение функции f(x) на отрезке [3/4;2]")

for i in range(6):
    print(integral(f, np.float64(3/4), 2, 0.1 * 0.1**i))
    
"""Мы видим, что при уменьшении dx уменьшается разница между аналитическим решением и тремя численными выше. Происходит это
за счёт увеличения числа шагов N и числа точек xk."""

1.1107207345395915 - аналитическое решение функции f(x) на отрезке [3/4;2]
0.8238512126812755, 0.8098258036743812, 0.7737705910624484 при шаге интегрирования 0.1
1.0322244184751246, 1.0312903460191785, 1.0212859253328779 при шаге интегрирования 0.010000000000000002
1.0887148327101404, 1.088627061795969, 1.072525102066485 при шаге интегрирования 0.0010000000000000002
1.1040534034851663, 1.1040446838813676, 1.0989731743454727 при шаге интегрирования 0.00010000000000000003
inf, 1.1086409328324405, 1.1070394070810448 при шаге интегрирования 1.0000000000000003e-05
inf, 1.1100661882097627, 1.1095599697750977 при шаге интегрирования 1.0000000000000004e-06


C:\Users\Fernando\AppData\Local\Temp\ipykernel_2212\96352255.py:2: RuntimeWarning: divide by zero encountered in divide
  return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)


'Мы видим, что при уменьшении dx уменьшается разница между аналитическим решением и тремя численными выше. Происходит это\nза счёт увеличения числа шагов N и числа точек xk.'